'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateAccount
    
    '''<summary>
    '''formCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formCreateAccount As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lbFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFirstName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbUpdateFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbUpdateLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateLastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbUpdateEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPassword As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbUpdatePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdatePassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNewPassword As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNewPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PreviousPage property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property PreviousPage() As Manga.UserLogin
        Get
            Return CType(MyBase.PreviousPage,Manga.UserLogin)
        End Get
    End Property
End Class
